spring:
# 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/bamboos?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 3
      max-active: 8
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.jpg,*.css,druid/*"
# redis 数据源配置
  redis:
    jedis:
      pool:
        max-active: 8
        min-idle: 4
        max-idle: 8
    host: 39.105.172.24
    port: 6379
    database: 4
    timeout: 3000
# mybatis 配置
mybatis-plus:
  mapper-locations: /mapperxml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
